# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/omi290/flyrank-ml-internship/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*



## Chosen Lane
Content Refresh & SEO Optimization

## ML Task Type
**Classification**

The objective is to classify webpages into categories such as **High Priority** or **Low Priority** for content refresh based on historical search performance metrics.

Each prediction helps identify which pages are most likely to benefit from optimization efforts.

This is a supervised machine learning problem because the model learns patterns from historical data to make predictions for unseen pages.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*



The ideal target would be whether a content refresh actually improved search performance.

Since the starter dataset does not contain future performance after a refresh, I will use a proxy target.

### Proxy Target

A page will be considered **High Priority** if it has:

- High impressions
- Low Click-Through Rate (CTR)
- Poor Average Position

Otherwise it will be considered **Low Priority**.

This proxy approximates which pages appear to have the greatest opportunity for improvement.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 3. Success metric

*One metric you can defend. What number means 'good'?*


Since this is framed as a classification problem, an appropriate evaluation metric is:

- Precision
- Recall
- F1 Score

Precision is particularly important because recommending unnecessary content updates wastes time and resources.

A useful model should correctly identify pages that genuinely deserve attention while minimizing false positives.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

In [2]:
!git clone https://github.com/omi290/flyrank-ml-internship.git

Cloning into 'flyrank-ml-internship'...
remote: Enumerating objects: 160, done.
remote: Counting objects: 100% (160/160), done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 160 (delta 52), reused 85 (delta 28), pack-reused 0 (from 0)
Receiving objects: 100% (160/160), 2.95 MiB | 18.50 MiB/s, done.
Resolving deltas: 100% (52/52), done.

In [3]:
%cd flyrank-ml-internship

/content/flyrank-ml-internship

In [4]:
import os

for root, dirs, files in os.walk("data"):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

data/raw/content_refresh_anonymized.csv

In [5]:
import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [6]:
import os

print(os.getcwd())
print(os.listdir())

/content/flyrank-ml-internship
['notebooks', 'work', 'AGENTS.md', 'skills', 'DATA_USE.md', 'scripts', '.github', 'LICENSE', '.gitignore', 'outputs', 'CLAUDE.md', 'data', 'README.md', 'submission', '.git', 'GUIDE.md', 'SETUP.md', 'requirements.txt', 'docs']

In [7]:
print("Rows:", len(df))
print("Columns:", len(df.columns))

df.head()

Rows: 30000
Columns: 44

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

# 4. Unit of Analysis

Each row in the dataset represents **one webpage**.

For every webpage, the dataset contains historical search metrics such as impressions, clicks, CTR, and average search position.

The machine learning model will make one prediction per webpage.

In [9]:
df["priority"] = (
    (df["ctr"] < df["ctr"].median()) &
    (df["avg_position"] > df["avg_position"].median())
)

df["priority"] = df["priority"].map({True: "High Priority", False: "Low Priority"})

df[["ctr", "avg_position", "priority"]].head()

    ctr  avg_position       priority
0  0.76          10.6   Low Priority
1  0.05          20.3  High Priority
2  0.09          36.5   Low Priority
3  0.49           6.2   Low Priority
4  0.13          44.0   Low Priority

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*



A fixed rule such as "refresh every page with CTR below 2%" ignores many other factors that influence search performance.

Machine learning can learn relationships among multiple metrics, including impressions, CTR, clicks, and average position.

By considering these variables together, an ML model can produce more informed recommendations than a single manually chosen threshold.

The model is intended to support decision-making rather than replace human judgment.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.